### ISSUE TITLE
Not compatible from dmn-js version 0.7.0

### ISSUE THREAD

**Issue by romero83** [camunda/camunda-dmn-xlsx#1]
Hi,

The current implementation v0.1.0 is not compatible from dmn-js version 0.7.0.

**Comment by ThorbenLindhauer** [comment]
Thanks for reporting. Is that due to the changed namespace or is there any other problem?

**Comment by romero83** [comment]
Yes, it is related only to the namespace change.

**Comment by ThorbenLindhauer** [comment]
I think I fixed this. Feel free to try out version 0.2.0-SNAPSHOT available in the [Camunda Nexus](https://app.camunda.com/nexus/content/groups/public/org/camunda/bpm/extension/dmn/).
