### ISSUE TITLE
Nullpointer exception parsing files from Excel online, OpenOffice, Etc

### ISSUE THREAD

**Issue by daviddelucca** [camunda/camunda-dmn-xlsx#2]
Hello folks!

We are using camunda-dmn-xlsx to convert a XLSX to DMN File and we are getting a NullPointerException [here](https://github.com/camunda/camunda-dmn-xlsx/blob/master/xlsx-dmn-converter/src/main/java/org/camunda/bpm/dmn/xlsx/XlsxConverter.java#L55) 

The problem is quite simple: only excel using on Windows includes the tag *<TitlesOfParts>*. We did an override on this function and solved our problem. 

```
if(properties.getTitleOfParts() != null).... 
```

We can open a PR here to solve it but i'm not sure if it will affect other points. Do you have other suggestion or agree with our solution?

**Comment by ThorbenLindhauer** [comment]
Thanks for reporting. Sure, please provide a pull request. The work sheet name that is extracted in this line of code is later used as the ID of the extracted decision. I guess there can be valid xlsx files with a single worksheet that don't require worksheet names. It should be fine to use a default worksheet name then.

**Comment by daviddelucca** [comment]
I'll do that! Ty

**Comment by ThorbenLindhauer** [comment]
Thank you for your contribution. I'll build a patch release next week.

**Comment by ThorbenLindhauer** [comment]
You can try out version 0.1.1 now that should contain your fix.
