### ISSUE TITLE
Convert number ranges

### ISSUE THREAD

**Issue by rolandHD** [camunda/camunda-dmn-xlsx#5]
This is a missing feature in the converter. It isn't able to detect number ranges and treat them accordingly.

I want to convert an Excel file into a DMN file using the XLSXConverter (camunda-dmn-xlsx)

-  This works for single numbers. if I use digits and expression like <,> >= and so on, the Converter converts correctly into numeric values/expressions

- but if I define a range of digits (e.g. [8000..1000]) 
the converter converts into a String using quotes e.g. "[8000..10000]" and this leads to a runtime exception (see https://forum.bpmn.io/t/feelconvertexception-feel-01015/17082). 

So I have to remove the quotes "" after conversion manually

**Comment by ThorbenLindhauer** [comment]
Hey Roland,

I just implemented this via https://github.com/camunda/camunda-dmn-xlsx/commit/4e1e4a1a0a03f9fba84b8a373ed0d1e52603c014.

You can try out the version 0.1.2-SNAPSHOT available at https://app.camunda.com/nexus/content/groups/public/org/camunda/bpm/extension/dmn/
