### ISSUE TITLE
CLI Converter creating wrong xmlns string and not working with 1.14 Camunda Modeler

### ISSUE THREAD

**Issue by patozgg** [camunda/camunda-dmn-xlsx#7]
Hallo, 

While using the CLI converter to create a DMN file from an Excel file I bumped into a possible issue. It appears that the converter is  creating the xmlns string like this "http://www.omg.org/spec/DMN/20151101/dmn11.xsd" when it should be "http://www.omg.org/spec/DMN/20151101/dmn.xsd".  This is causing the dmn file not to be viewable in the modeler. 

Please see image for your reference. 
![image](https://user-images.githubusercontent.com/32462592/39388232-b9f5d4f2-4a3b-11e8-9fba-835134221cd2.png)

Please let me know if you have any questions. 

Thank you,

**Comment by ThorbenLindhauer** [comment]
Thanks for reporting. This should be already fixed in version 0.1.1, which you can find here: https://app.camunda.com/nexus/content/groups/public/org/camunda/bpm/extension/dmn/dmn-xlsx-cli/0.1.1/. The README still links to 0.1.0 which I will update in a second.
