### ISSUE TITLE
upgrade docx4j depedency

### ISSUE THREAD

**Issue by heltewig-fisp** [camunda/camunda-dmn-xlsx#9]
Please consider upgrading to a more recent stable version of docx4j, such as docx4j 3.3.7 (which in turn uses more recent libraries with bugfixes and security improvements).
Maybe this could be done when upgrading the camunda dependencies?

**Comment by ThorbenLindhauer** [comment]
Upgrading dependencies is always a good idea. Would you like to submit a pull request for that?
